#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: 750e50d
#
Name     : librist
Version  : 0.2.9
Release  : 2
URL      : https://code.videolan.org/rist/librist/-/archive/v0.2.9/librist-v0.2.9.tar.gz
Source0  : https://code.videolan.org/rist/librist/-/archive/v0.2.9/librist-v0.2.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: librist-bin = %{version}-%{release}
Requires: librist-lib = %{version}-%{release}
Requires: librist-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(libcjson)
BuildRequires : pkgconfig(libmicrohttpd)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
![librist logo](docs/librist_logo.png)
# librist
A library that can be used to easily add the RIST protocol to your application.

%package bin
Summary: bin components for the librist package.
Group: Binaries
Requires: librist-license = %{version}-%{release}

%description bin
bin components for the librist package.


%package dev
Summary: dev components for the librist package.
Group: Development
Requires: librist-lib = %{version}-%{release}
Requires: librist-bin = %{version}-%{release}
Provides: librist-devel = %{version}-%{release}
Requires: librist = %{version}-%{release}

%description dev
dev components for the librist package.


%package lib
Summary: lib components for the librist package.
Group: Libraries
Requires: librist-license = %{version}-%{release}

%description lib
lib components for the librist package.


%package license
Summary: license components for the librist package.
Group: Default

%description license
license components for the librist package.


%prep
%setup -q -n librist-v0.2.9
cd %{_builddir}/librist-v0.2.9
pushd ..
cp -a librist-v0.2.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707085042
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/librist
cp %{_builddir}/librist-v%{version}/contrib/mbedtls/LICENSE %{buildroot}/usr/share/package-licenses/librist/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/rist2rist
/V3/usr/bin/ristreceiver
/V3/usr/bin/ristsender
/V3/usr/bin/ristsrppasswd
/usr/bin/rist2rist
/usr/bin/ristreceiver
/usr/bin/ristsender
/usr/bin/ristsrppasswd

%files dev
%defattr(-,root,root,-)
/usr/include/librist/common.h
/usr/include/librist/headers.h
/usr/include/librist/librist.h
/usr/include/librist/librist_config.h
/usr/include/librist/librist_srp.h
/usr/include/librist/logging.h
/usr/include/librist/oob.h
/usr/include/librist/opt.h
/usr/include/librist/peer.h
/usr/include/librist/receiver.h
/usr/include/librist/sender.h
/usr/include/librist/stats.h
/usr/include/librist/udpsocket.h
/usr/include/librist/urlparam.h
/usr/include/librist/version.h
/usr/lib64/librist.so
/usr/lib64/pkgconfig/librist.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/librist.so.4.3.0
/usr/lib64/librist.so.4
/usr/lib64/librist.so.4.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librist/2b8b815229aa8a61e483fb4ba0588b8b6c491890
